name: Deploy ShinyDex
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # On précise où se trouve le cache npm
          cache-dependency-path: 'ShinyDex-Site/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ShinyDex-Site # <--- ICI

      - name: Build project
        run: npm run build
        working-directory: ShinyDex-Site # <--- ICI

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # On pointe vers le dossier dist à l'intérieur du sous-dossier
          path: 'ShinyDex-Site/dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4